# Use the official Postgres image as a base
FROM postgres:latest

# Environment variables are defined in the .env file, no need to redeclare here

# Expose the port Postgres listens on
EXPOSE 5432

# The CMD instruction is already defined in the base image